import type { SkillProfile } from '@/types'

export const skillsLibrary: SkillProfile[] = [
  /* ═══════════════════════════════════════════════════════
     TECNOLOGÍA (10 perfiles)
  ═══════════════════════════════════════════════════════ */
  {
    id: 'tech-frontend-senior',
    rubro: 'Tecnología',
    perfil: 'Frontend Developer',
    nivel: 'Senior',
    skills: {
      tecnicas: ['React', 'TypeScript', 'Next.js', 'HTML5', 'CSS3', 'GraphQL', 'REST APIs', 'Testing'],
      blandas: ['Trabajo en equipo', 'Comunicación', 'Resolución de problemas', 'Atención al detalle'],
      herramientas: ['Git', 'Webpack', 'Vite', 'Jest', 'Figma', 'VS Code', 'Chrome DevTools'],
      certificaciones: [],
    },
    descripcionTipica: 'Desarrollador frontend con experiencia en React y TypeScript. Capaz de liderar proyectos y mentorear juniors.',
  },
  {
    id: 'tech-backend-senior',
    rubro: 'Tecnología',
    perfil: 'Backend Developer',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Node.js', 'Python', 'PostgreSQL', 'MongoDB', 'Redis', 'Docker', 'REST APIs', 'GraphQL', 'Microservices'],
      blandas: ['Pensamiento analítico', 'Autonomía', 'Documentación', 'Liderazgo técnico'],
      herramientas: ['Git', 'Docker', 'Kubernetes', 'AWS', 'Postman', 'Swagger'],
      certificaciones: ['AWS Certified Developer'],
    },
    descripcionTipica: 'Desarrollador backend con sólida experiencia en APIs y bases de datos. Experiencia en arquitecturas escalables.',
  },
  {
    id: 'tech-fullstack-semi',
    rubro: 'Tecnología',
    perfil: 'Fullstack Developer',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'REST APIs', 'MongoDB'],
      blandas: ['Versatilidad', 'Aprendizaje continuo', 'Colaboración', 'Proactividad'],
      herramientas: ['Git', 'Docker', 'VS Code', 'Postman', 'Jira'],
      certificaciones: [],
    },
    descripcionTipica: 'Desarrollador con capacidades tanto frontend como backend. Perfil versátil para equipos pequeños y medianos.',
  },
  {
    id: 'tech-devops-senior',
    rubro: 'Tecnología',
    perfil: 'DevOps / SRE Engineer',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Docker', 'Kubernetes', 'CI/CD', 'Terraform', 'Ansible', 'Linux', 'Bash', 'Monitoring'],
      blandas: ['Proactividad', 'Gestión de incidentes', 'Documentación', 'Comunicación bajo presión'],
      herramientas: ['Jenkins', 'GitHub Actions', 'AWS', 'GCP', 'Datadog', 'Prometheus', 'Grafana'],
      certificaciones: ['AWS Solutions Architect', 'CKA'],
    },
    descripcionTipica: 'Ingeniero DevOps con experiencia en infraestructura como código y pipelines CI/CD.',
  },
  {
    id: 'tech-data-scientist',
    rubro: 'Tecnología',
    perfil: 'Data Scientist',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Python', 'Machine Learning', 'SQL', 'TensorFlow', 'Pandas', 'NumPy', 'Estadística', 'NLP'],
      blandas: ['Pensamiento analítico', 'Comunicación de resultados', 'Curiosidad intelectual'],
      herramientas: ['Jupyter', 'Power BI', 'Tableau', 'Git', 'Spark', 'Airflow'],
      certificaciones: ['Google Data Analytics', 'IBM Data Science'],
    },
    descripcionTipica: 'Científico de datos con experiencia en modelos predictivos y análisis estadístico.',
  },
  {
    id: 'tech-mobile-senior',
    rubro: 'Tecnología',
    perfil: 'Mobile Developer (iOS/Android)',
    nivel: 'Senior',
    skills: {
      tecnicas: ['React Native', 'Swift', 'Kotlin', 'Expo', 'iOS SDK', 'Android SDK', 'REST APIs', 'Firebase'],
      blandas: ['Atención al detalle', 'Creatividad UX', 'Autonomía'],
      herramientas: ['Xcode', 'Android Studio', 'Git', 'Fastlane', 'TestFlight'],
      certificaciones: ['Google Associate Android Developer'],
    },
    descripcionTipica: 'Desarrollador mobile con experiencia en apps nativas e híbridas para iOS y Android.',
  },
  {
    id: 'tech-cloud-architect',
    rubro: 'Tecnología',
    perfil: 'Cloud Architect',
    nivel: 'Lead',
    skills: {
      tecnicas: ['AWS', 'GCP', 'Azure', 'Terraform', 'Serverless', 'Microservices', 'Networking', 'Security'],
      blandas: ['Visión estratégica', 'Liderazgo', 'Comunicación ejecutiva', 'Gestión del cambio'],
      herramientas: ['CloudFormation', 'Pulumi', 'Datadog', 'PagerDuty'],
      certificaciones: ['AWS Solutions Architect Professional', 'Google Professional Cloud Architect'],
    },
    descripcionTipica: 'Arquitecto cloud con experiencia diseñando infraestructuras escalables, seguras y costo-eficientes.',
  },
  {
    id: 'tech-qa-semi',
    rubro: 'Tecnología',
    perfil: 'QA Engineer / Tester',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Testing manual', 'Automatización de pruebas', 'Selenium', 'Cypress', 'API Testing', 'Performance Testing'],
      blandas: ['Atención al detalle', 'Pensamiento crítico', 'Comunicación', 'Organización'],
      herramientas: ['JIRA', 'Postman', 'Selenium', 'Cypress', 'JMeter', 'TestRail'],
      certificaciones: ['ISTQB Foundation'],
    },
    descripcionTipica: 'QA Engineer con experiencia en pruebas manuales y automatizadas para aplicaciones web y móviles.',
  },
  {
    id: 'tech-cybersecurity-senior',
    rubro: 'Tecnología',
    perfil: 'Cybersecurity Analyst',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Penetration Testing', 'SIEM', 'ISO 27001', 'OWASP', 'Ethical Hacking', 'Incident Response', 'Firewall'],
      blandas: ['Ética profesional', 'Atención al detalle', 'Pensamiento crítico', 'Gestión del riesgo'],
      herramientas: ['Nessus', 'Burp Suite', 'Wireshark', 'Splunk', 'Metasploit'],
      certificaciones: ['CISSP', 'CEH', 'CompTIA Security+'],
    },
    descripcionTipica: 'Analista de ciberseguridad con experiencia en protección de infraestructuras y respuesta a incidentes.',
  },
  {
    id: 'tech-ml-engineer',
    rubro: 'Tecnología',
    perfil: 'ML Engineer / AI Engineer',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Python', 'TensorFlow', 'PyTorch', 'MLOps', 'Feature Engineering', 'LLMs', 'RAG', 'API Design'],
      blandas: ['Investigación', 'Síntesis de información', 'Comunicación técnica'],
      herramientas: ['MLflow', 'Weights & Biases', 'Hugging Face', 'Docker', 'Kubernetes', 'Vertex AI'],
      certificaciones: ['Google Professional ML Engineer'],
    },
    descripcionTipica: 'Ingeniero de ML con experiencia en llevar modelos de investigación a producción escalable.',
  },

  /* ═══════════════════════════════════════════════════════
     MARKETING DIGITAL (10 perfiles)
  ═══════════════════════════════════════════════════════ */
  {
    id: 'marketing-digital-senior',
    rubro: 'Marketing',
    perfil: 'Marketing Digital Manager',
    nivel: 'Senior',
    skills: {
      tecnicas: ['SEO', 'SEM', 'Google Ads', 'Meta Ads', 'Email Marketing', 'Analítica Web', 'CRO', 'Growth'],
      blandas: ['Creatividad', 'Orientación a resultados', 'Gestión de proyectos', 'Liderazgo'],
      herramientas: ['Google Analytics 4', 'HubSpot', 'Mailchimp', 'Semrush', 'Canva', 'Meta Business Suite'],
      certificaciones: ['Google Ads', 'Meta Blueprint', 'HubSpot Marketing'],
    },
    descripcionTipica: 'Especialista en marketing digital con foco en performance y estrategias data-driven.',
  },
  {
    id: 'marketing-content-semi',
    rubro: 'Marketing',
    perfil: 'Content Strategist',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Redacción SEO', 'Estrategia de contenidos', 'Redes Sociales', 'Copywriting', 'Storytelling', 'Keyword Research'],
      blandas: ['Creatividad', 'Escritura', 'Adaptabilidad', 'Empatía con la audiencia'],
      herramientas: ['WordPress', 'Canva', 'Hootsuite', 'Buffer', 'Notion', 'Ahrefs'],
      certificaciones: ['HubSpot Content Marketing'],
    },
    descripcionTipica: 'Especialista en creación y distribución de contenidos para medios digitales.',
  },
  {
    id: 'marketing-seo-semi',
    rubro: 'Marketing',
    perfil: 'SEO Specialist',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['SEO On-Page', 'SEO Off-Page', 'Technical SEO', 'Link Building', 'Keyword Research', 'Core Web Vitals'],
      blandas: ['Analítico', 'Paciencia', 'Actualización constante', 'Atención al detalle'],
      herramientas: ['Semrush', 'Ahrefs', 'Google Search Console', 'Screaming Frog', 'Google Analytics'],
      certificaciones: ['Google Analytics', 'Semrush SEO Toolkit'],
    },
    descripcionTipica: 'Especialista SEO con experiencia en posicionamiento orgánico y auditorías técnicas.',
  },
  {
    id: 'marketing-performance-senior',
    rubro: 'Marketing',
    perfil: 'Performance Marketing Manager',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Google Ads', 'Meta Ads', 'TikTok Ads', 'Programmatic', 'Retargeting', 'Attribution', 'CPA/ROAS'],
      blandas: ['Orientación a resultados', 'Toma de decisiones data-driven', 'Gestión de presupuesto'],
      herramientas: ['Google Ads Manager', 'Meta Ads Manager', 'Google Analytics 4', 'Data Studio', 'Adjust'],
      certificaciones: ['Google Ads Certified', 'Meta Blueprint'],
    },
    descripcionTipica: 'Manager de performance marketing con experiencia en campañas de paid media a gran escala.',
  },
  {
    id: 'marketing-growth-semi',
    rubro: 'Marketing',
    perfil: 'Growth Hacker',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['A/B Testing', 'Funnel Optimization', 'Viral Loops', 'Product Analytics', 'Email Automation', 'Referral Programs'],
      blandas: ['Experimentación', 'Creatividad', 'Pensamiento lateral', 'Velocidad de ejecución'],
      herramientas: ['Mixpanel', 'Amplitude', 'Hotjar', 'Optimizely', 'Segment'],
      certificaciones: [],
    },
    descripcionTipica: 'Growth hacker con mentalidad de experimentación continua y foco en métricas de crecimiento.',
  },
  {
    id: 'marketing-community-junior',
    rubro: 'Marketing',
    perfil: 'Community Manager',
    nivel: 'Junior',
    skills: {
      tecnicas: ['Gestión de redes sociales', 'Redacción', 'Diseño básico', 'Atención al cliente online', 'Métricas sociales'],
      blandas: ['Empatía', 'Creatividad', 'Puntualidad', 'Comunicación'],
      herramientas: ['Hootsuite', 'Buffer', 'Canva', 'Instagram', 'TikTok', 'Facebook'],
      certificaciones: [],
    },
    descripcionTipica: 'Community manager con foco en engagement y gestión de comunidades digitales en LATAM.',
  },
  {
    id: 'marketing-email-semi',
    rubro: 'Marketing',
    perfil: 'Email Marketing Specialist',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Email Marketing', 'Automatización', 'Segmentación', 'HTML para emails', 'A/B Testing', 'Deliverability'],
      blandas: ['Atención al detalle', 'Escritura persuasiva', 'Organización'],
      herramientas: ['Mailchimp', 'HubSpot', 'Klaviyo', 'SendGrid', 'ActiveCampaign'],
      certificaciones: ['HubSpot Email Marketing'],
    },
    descripcionTipica: 'Especialista en email marketing con experiencia en ciclos de vida del cliente y automatización.',
  },
  {
    id: 'marketing-brand-senior',
    rubro: 'Marketing',
    perfil: 'Brand Manager',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Estrategia de marca', 'Investigación de mercado', 'Posicionamiento', 'Desarrollo de campañas', 'P&L'],
      blandas: ['Visión estratégica', 'Liderazgo creativo', 'Gestión de agencias', 'Presentación ejecutiva'],
      herramientas: ['Nielsen', 'Kantar', 'MS Office', 'Adobe Creative Suite'],
      certificaciones: [],
    },
    descripcionTipica: 'Brand manager con experiencia en construcción y gestión de marcas en mercados LATAM.',
  },
  {
    id: 'marketing-ecommerce-semi',
    rubro: 'Marketing',
    perfil: 'E-commerce Manager',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['E-commerce', 'Shopify', 'WooCommerce', 'Marketplace (MeLi/Amazon)', 'UX/CRO', 'Analytics', 'Logística'],
      blandas: ['Orientación al cliente', 'Pensamiento analítico', 'Gestión de proyectos'],
      herramientas: ['Shopify', 'Google Analytics', 'Hotjar', 'MercadoLibre', 'Amazon Seller'],
      certificaciones: ['Shopify Partner'],
    },
    descripcionTipica: 'E-commerce manager con experiencia en tiendas propias y marketplaces en LATAM.',
  },
  {
    id: 'marketing-influencer-junior',
    rubro: 'Marketing',
    perfil: 'Influencer Marketing Specialist',
    nivel: 'Junior',
    skills: {
      tecnicas: ['Identificación de influencers', 'Briefing creativo', 'Negociación', 'Métricas de influencia', 'UGC'],
      blandas: ['Networking', 'Creatividad', 'Comunicación', 'Tendencias digitales'],
      herramientas: ['HypeAuditor', 'Kolsquare', 'Instagram', 'TikTok', 'YouTube'],
      certificaciones: [],
    },
    descripcionTipica: 'Especialista en estrategias de influencer marketing para marcas en mercados LATAM.',
  },

  /* ═══════════════════════════════════════════════════════
     VENTAS / COMERCIAL (10 perfiles)
  ═══════════════════════════════════════════════════════ */
  {
    id: 'ventas-ejecutivo-senior',
    rubro: 'Ventas',
    perfil: 'Ejecutivo de Ventas B2B',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Negociación', 'CRM', 'Prospección', 'Cierre de ventas', 'Pipeline management', 'Ventas consultivas'],
      blandas: ['Persuasión', 'Resiliencia', 'Orientación al cliente', 'Empatía', 'Escucha activa'],
      herramientas: ['Salesforce', 'HubSpot CRM', 'LinkedIn Sales Navigator', 'Zoom', 'Apollo.io'],
      certificaciones: ['Salesforce Sales Cloud'],
    },
    descripcionTipica: 'Ejecutivo de ventas con historial probado en superación de cuotas y gestión de cuentas B2B.',
  },
  {
    id: 'ventas-sdr-junior',
    rubro: 'Ventas',
    perfil: 'SDR (Sales Development Rep)',
    nivel: 'Junior',
    skills: {
      tecnicas: ['Prospección outbound', 'Cold calling', 'Email outreach', 'Calificación de leads', 'CRM'],
      blandas: ['Perseverancia', 'Comunicación', 'Curiosidad', 'Energía'],
      herramientas: ['HubSpot', 'Salesloft', 'Apollo.io', 'LinkedIn', 'Zoom'],
      certificaciones: [],
    },
    descripcionTipica: 'SDR con enfoque en generación y calificación de oportunidades de negocio B2B.',
  },
  {
    id: 'ventas-account-executive-semi',
    rubro: 'Ventas',
    perfil: 'Account Executive',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Ventas SaaS', 'Demo de producto', 'Negociación', 'Contract management', 'Upselling', 'Cross-selling'],
      blandas: ['Orientación al cliente', 'Storytelling', 'Gestión del tiempo', 'Autonomía'],
      herramientas: ['Salesforce', 'HubSpot', 'Zoom', 'DocuSign', 'Notion'],
      certificaciones: [],
    },
    descripcionTipica: 'Account executive con experiencia en ciclos de venta complejos y gestión de cuentas enterprise.',
  },
  {
    id: 'ventas-kam-senior',
    rubro: 'Ventas',
    perfil: 'Key Account Manager',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Gestión de cuentas clave', 'Planificación de negocios', 'Forecasting', 'P&L de cuenta', 'Negociación estratégica'],
      blandas: ['Relacionamiento ejecutivo', 'Empatía', 'Orientación a largo plazo', 'Liderazgo'],
      herramientas: ['Salesforce', 'SAP', 'Power BI', 'MS Office'],
      certificaciones: [],
    },
    descripcionTipica: 'Key Account Manager con experiencia en gestión de relaciones a largo plazo con clientes estratégicos.',
  },
  {
    id: 'ventas-inside-semi',
    rubro: 'Ventas',
    perfil: 'Inside Sales Representative',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Ventas remotas', 'Demo virtual', 'Objeciones', 'CRM', 'Pipeline', 'Email sequences'],
      blandas: ['Comunicación digital', 'Autodisciplina', 'Persuasión', 'Adaptabilidad'],
      herramientas: ['HubSpot', 'Zoom', 'Outreach', 'LinkedIn', 'Calendly'],
      certificaciones: [],
    },
    descripcionTipica: 'Inside sales con experiencia en ventas remotas y gestión de ciclos cortos de decisión.',
  },
  {
    id: 'ventas-director-senior',
    rubro: 'Ventas',
    perfil: 'Director Comercial / Head of Sales',
    nivel: 'Lead',
    skills: {
      tecnicas: ['Estrategia comercial', 'Gestión de equipos', 'Forecasting', 'Revenue Operations', 'Go-to-market'],
      blandas: ['Liderazgo', 'Visión estratégica', 'Coaching', 'Comunicación ejecutiva'],
      herramientas: ['Salesforce', 'HubSpot', 'Power BI', 'Gong', 'Clari'],
      certificaciones: [],
    },
    descripcionTipica: 'Director comercial con experiencia liderando equipos de ventas y escalando ingresos en LATAM.',
  },
  {
    id: 'ventas-retail-semi',
    rubro: 'Ventas',
    perfil: 'Ejecutivo de Ventas Retail',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Ventas en piso', 'Atención al cliente', 'Visual merchandising', 'Gestión de inventario', 'POS'],
      blandas: ['Orientación al servicio', 'Empatía', 'Trabajo en equipo', 'Proactividad'],
      herramientas: ['POS/TPV', 'SAP', 'Excel'],
      certificaciones: [],
    },
    descripcionTipica: 'Ejecutivo retail con experiencia en venta de piso y gestión de tienda.',
  },
  {
    id: 'ventas-preventista-junior',
    rubro: 'Ventas',
    perfil: 'Preventista / Vendedor de Ruta',
    nivel: 'Junior',
    skills: {
      tecnicas: ['Venta de ruta', 'Gestión de cartera', 'Toma de pedidos', 'Merchandising', 'Cobranzas'],
      blandas: ['Organización', 'Puntualidad', 'Resiliencia', 'Orientación al resultado'],
      herramientas: ['App móvil de pedidos', 'GPS', 'Excel'],
      certificaciones: [],
    },
    descripcionTipica: 'Preventista con experiencia en gestión de ruta y mantenimiento de cartera de clientes.',
  },
  {
    id: 'ventas-presales-semi',
    rubro: 'Ventas',
    perfil: 'Presales / Sales Engineer',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Demo técnica', 'Proof of Concept', 'Arquitectura de soluciones', 'Respuesta a RFP', 'Integración de sistemas'],
      blandas: ['Comunicación técnica', 'Empatía con el cliente', 'Presentación ejecutiva'],
      herramientas: ['Salesforce', 'Zoom', 'Miro', 'Postman', 'Confluence'],
      certificaciones: [],
    },
    descripcionTipica: 'Presales engineer con capacidad de traducir necesidades del cliente en soluciones técnicas.',
  },
  {
    id: 'ventas-trade-marketing-semi',
    rubro: 'Ventas',
    perfil: 'Trade Marketing Analyst',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Ejecución en punto de venta', 'Análisis de sell-out', 'Categoría', 'BTL', 'Shopper marketing'],
      blandas: ['Analítico', 'Creatividad', 'Trabajo en equipo', 'Gestión de proyectos'],
      herramientas: ['Nielsen', 'SAP', 'Power BI', 'Excel'],
      certificaciones: [],
    },
    descripcionTipica: 'Trade marketing analyst con experiencia en ejecución en punto de venta y análisis de categoría.',
  },

  /* ═══════════════════════════════════════════════════════
     FINANZAS / CONTABILIDAD (10 perfiles)
  ═══════════════════════════════════════════════════════ */
  {
    id: 'finanzas-analista-semi',
    rubro: 'Finanzas',
    perfil: 'Analista Financiero',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Contabilidad', 'Excel Avanzado', 'Análisis financiero', 'Presupuestación', 'Forecasting', 'Valuación'],
      blandas: ['Atención al detalle', 'Pensamiento analítico', 'Ética profesional', 'Organización'],
      herramientas: ['Excel', 'SAP', 'Power BI', 'QuickBooks', 'Bloomberg'],
      certificaciones: ['CPA', 'CFA nivel 1'],
    },
    descripcionTipica: 'Analista financiero con experiencia en modelado financiero y análisis de rentabilidad.',
  },
  {
    id: 'finanzas-contador-senior',
    rubro: 'Finanzas',
    perfil: 'Contador Público Senior',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Contabilidad general', 'IFRS/NIC', 'Impuestos', 'Auditoría', 'Estados financieros', 'Consolidación'],
      blandas: ['Ética', 'Rigor', 'Trabajo bajo presión', 'Atención al detalle'],
      herramientas: ['SAP', 'Oracle', 'Excel Avanzado', 'Tango/Bejerman'],
      certificaciones: ['CPA', 'Matrícula profesional'],
    },
    descripcionTipica: 'Contador público con sólida experiencia en contabilidad corporativa y cumplimiento impositivo.',
  },
  {
    id: 'finanzas-controller-senior',
    rubro: 'Finanzas',
    perfil: 'Controller Financiero',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Control de gestión', 'Reporting', 'KPIs financieros', 'Budget', 'Forecast', 'Análisis de variaciones'],
      blandas: ['Liderazgo', 'Comunicación ejecutiva', 'Pensamiento estratégico'],
      herramientas: ['SAP', 'Power BI', 'Hyperion', 'Cognos', 'Excel'],
      certificaciones: ['CPA', 'ACCA'],
    },
    descripcionTipica: 'Controller con experiencia en control de gestión, reporting ejecutivo y análisis financiero.',
  },
  {
    id: 'finanzas-tesorero-senior',
    rubro: 'Finanzas',
    perfil: 'Tesorero / Treasury Manager',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Gestión de caja', 'Operaciones FX', 'Financiamiento', 'Cash flow', 'Inversiones', 'Riesgo financiero'],
      blandas: ['Precisión', 'Toma de decisiones', 'Negociación bancaria', 'Discreción'],
      herramientas: ['SAP Treasury', 'Bloomberg', 'Excel', 'Sistemas bancarios'],
      certificaciones: ['CTP (Certified Treasury Professional)'],
    },
    descripcionTipica: 'Tesorero con experiencia en gestión de liquidez, operaciones FX y relaciones bancarias.',
  },
  {
    id: 'finanzas-auditor-semi',
    rubro: 'Finanzas',
    perfil: 'Auditor Interno / Externo',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Auditoría financiera', 'Control interno', 'Riesgo operacional', 'SOX', 'COSO', 'Papeles de trabajo'],
      blandas: ['Integridad', 'Escepticismo profesional', 'Comunicación escrita', 'Organización'],
      herramientas: ['ACL/IDEA', 'SAP', 'Excel', 'TeamMate'],
      certificaciones: ['CIA', 'CPA', 'CISA'],
    },
    descripcionTipica: 'Auditor con experiencia en auditorías financieras y evaluación de controles internos.',
  },
  {
    id: 'finanzas-costos-semi',
    rubro: 'Finanzas',
    perfil: 'Analista de Costos',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Contabilidad de costos', 'Costeo ABC', 'Análisis de margen', 'Presupuesto de producción', 'Varianzas'],
      blandas: ['Atención al detalle', 'Trabajo en equipo con producción', 'Analítico'],
      herramientas: ['SAP CO', 'Excel', 'Power BI'],
      certificaciones: [],
    },
    descripcionTipica: 'Analista de costos con experiencia en costeo de productos y análisis de rentabilidad por línea.',
  },
  {
    id: 'finanzas-impuestos-senior',
    rubro: 'Finanzas',
    perfil: 'Especialista Impositivo / Tax Manager',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Impuesto a las ganancias', 'IVA', 'Ingresos brutos', 'Precio de transferencia', 'Planeamiento fiscal'],
      blandas: ['Actualización constante', 'Ética', 'Comunicación', 'Precisión'],
      herramientas: ['AFIP/SAT sistemas', 'SAP FI', 'Excel', 'Errepar/IBFD'],
      certificaciones: ['CPA', 'Especialización en tributación'],
    },
    descripcionTipica: 'Especialista impositivo con profundo conocimiento de las obligaciones fiscales en LATAM.',
  },
  {
    id: 'finanzas-fp-senior',
    rubro: 'Finanzas',
    perfil: 'FP&A Analyst / Manager',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Financial Planning', 'Análisis de negocio', 'Modelado financiero', 'Presentaciones a board', 'Driver-based planning'],
      blandas: ['Storytelling con datos', 'Influencia sin autoridad', 'Pensamiento estratégico'],
      herramientas: ['Anaplan', 'Adaptive Insights', 'Power BI', 'Excel', 'Tableau'],
      certificaciones: ['FP&A Certification (AFP)'],
    },
    descripcionTipica: 'FP&A manager con experiencia en planificación financiera y soporte a la toma de decisiones.',
  },
  {
    id: 'finanzas-inversiones-semi',
    rubro: 'Finanzas',
    perfil: 'Analista de Inversiones',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Valuación de empresas', 'DCF', 'Comparables', 'Análisis sectorial', 'Due Diligence', 'M&A'],
      blandas: ['Pensamiento analítico', 'Síntesis', 'Presentaciones ejecutivas'],
      herramientas: ['Bloomberg', 'Capital IQ', 'Excel', 'PowerPoint'],
      certificaciones: ['CFA Nivel 2', 'Series 7'],
    },
    descripcionTipica: 'Analista de inversiones con experiencia en valuación de empresas y análisis de mercados financieros.',
  },
  {
    id: 'finanzas-cfo-lead',
    rubro: 'Finanzas',
    perfil: 'CFO / Director Financiero',
    nivel: 'Lead',
    skills: {
      tecnicas: ['Estrategia financiera', 'Investor relations', 'M&A', 'Fundraising', 'Gestión de riesgos', 'Gobierno corporativo'],
      blandas: ['Liderazgo', 'Visión estratégica', 'Comunicación al board', 'Toma de decisiones bajo incertidumbre'],
      herramientas: ['ERP (SAP/Oracle)', 'Power BI', 'Bloomberg', 'PowerPoint'],
      certificaciones: ['CPA', 'MBA', 'CFA'],
    },
    descripcionTipica: 'CFO con experiencia liderando funciones financieras en empresas de mediana y gran escala en LATAM.',
  },

  /* ═══════════════════════════════════════════════════════
     RRHH (10 perfiles)
  ═══════════════════════════════════════════════════════ */
  {
    id: 'rrhh-recruiter-semi',
    rubro: 'RRHH',
    perfil: 'Recruiter / Talent Acquisition',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Sourcing', 'Entrevistas por competencias', 'Employer Branding', 'ATS', 'Headhunting', 'Onboarding'],
      blandas: ['Comunicación', 'Empatía', 'Organización', 'Negociación', 'Intuición sobre personas'],
      herramientas: ['LinkedIn Recruiter', 'Workday', 'Greenhouse', 'BambooHR', 'ConectAr Talento'],
      certificaciones: ['SHRM-CP'],
    },
    descripcionTipica: 'Recruiter con experiencia en búsqueda y selección de perfiles técnicos y comerciales.',
  },
  {
    id: 'rrhh-hrbp-senior',
    rubro: 'RRHH',
    perfil: 'HR Business Partner',
    nivel: 'Senior',
    skills: {
      tecnicas: ['People analytics', 'Gestión del desempeño', 'Desarrollo organizacional', 'Relaciones laborales', 'Planes de carrera'],
      blandas: ['Influencia sin autoridad', 'Escucha activa', 'Pensamiento sistémico', 'Coaching'],
      herramientas: ['Workday', 'SAP HCM', 'Power BI', 'SurveyMonkey'],
      certificaciones: ['SHRM-SCP', 'PHR'],
    },
    descripcionTipica: 'HRBP con experiencia en acompañar a líderes de negocio y gestionar el talento estratégicamente.',
  },
  {
    id: 'rrhh-capacitacion-semi',
    rubro: 'RRHH',
    perfil: 'Especialista en Capacitación',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Diseño instruccional', 'E-learning', 'Facilitación', 'Evaluación de impacto', 'LMS', 'Kirkpatrick'],
      blandas: ['Comunicación', 'Creatividad', 'Empatía', 'Adaptabilidad'],
      herramientas: ['Articulate 360', 'Moodle', 'LinkedIn Learning', 'Canva', 'Zoom'],
      certificaciones: ['ATD CPLP', 'Facilitación certificada'],
    },
    descripcionTipica: 'Especialista en capacitación con experiencia en diseño de programas de desarrollo y e-learning.',
  },
  {
    id: 'rrhh-compensaciones-senior',
    rubro: 'RRHH',
    perfil: 'Especialista en Compensaciones y Beneficios',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Estructuras salariales', 'Encuestas de mercado', 'Job grading', 'Incentivos variables', 'Beneficios LATAM'],
      blandas: ['Confidencialidad', 'Análisis cuantitativo', 'Comunicación', 'Equidad'],
      herramientas: ['Mercer', 'Willis Towers Watson', 'SAP HCM', 'Excel', 'Power BI'],
      certificaciones: ['CCP (Certified Compensation Professional)'],
    },
    descripcionTipica: 'Especialista C&B con experiencia en diseño de estructuras salariales competitivas para LATAM.',
  },
  {
    id: 'rrhh-payroll-semi',
    rubro: 'RRHH',
    perfil: 'Liquidador de Sueldos / Payroll Analyst',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Liquidación de sueldos', 'Legislación laboral', 'AFIP/IMSS/DIAN', 'Legajos', 'Cargas sociales'],
      blandas: ['Precisión', 'Discreción', 'Organización', 'Trabajo bajo presión en cierres'],
      herramientas: ['Visma', 'Tango', 'SAP HCM', 'Excel', 'AFIP Sicoss'],
      certificaciones: [],
    },
    descripcionTipica: 'Liquidador de sueldos con dominio de legislación laboral argentina/LATAM y herramientas de payroll.',
  },
  {
    id: 'rrhh-generalista-junior',
    rubro: 'RRHH',
    perfil: 'Generalista de RRHH',
    nivel: 'Junior',
    skills: {
      tecnicas: ['Reclutamiento básico', 'Administración de personal', 'Onboarding', 'Clima organizacional', 'Legajos'],
      blandas: ['Empatía', 'Confidencialidad', 'Organización', 'Servicio al empleado'],
      herramientas: ['BambooHR', 'Google Workspace', 'Excel', 'Notion'],
      certificaciones: [],
    },
    descripcionTipica: 'Generalista de RRHH con amplia cobertura de procesos del área y vocación de servicio.',
  },
  {
    id: 'rrhh-clima-semi',
    rubro: 'RRHH',
    perfil: 'Especialista en Cultura y Clima',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Encuestas de clima', 'Cultura organizacional', 'Employer branding', 'EVP', 'Comunicación interna'],
      blandas: ['Empatía', 'Creatividad', 'Facilitación', 'Escucha activa'],
      herramientas: ['Culture Amp', 'Gallup Q12', 'SurveyMonkey', 'Canva', 'Slack'],
      certificaciones: [],
    },
    descripcionTipica: 'Especialista en cultura organizacional con experiencia en diagnóstico y planes de mejora de clima.',
  },
  {
    id: 'rrhh-talent-management-senior',
    rubro: 'RRHH',
    perfil: 'Talent Management Specialist',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Evaluación de desempeño', 'Planes de desarrollo', 'Sucesión', 'High Potentials', 'Assessment center'],
      blandas: ['Visión de largo plazo', 'Coaching', 'Influencia', 'Comunicación ejecutiva'],
      herramientas: ['Workday', 'SuccessFactors', 'Cornerstone', 'Power BI'],
      certificaciones: ['Coaching ICF', 'DISC Certificado'],
    },
    descripcionTipica: 'Talent manager con experiencia en gestión de desempeño, desarrollo y planes de sucesión.',
  },
  {
    id: 'rrhh-relaciones-laborales-senior',
    rubro: 'RRHH',
    perfil: 'Especialista en Relaciones Laborales',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Derecho laboral', 'Negociación sindical', 'CCT', 'Disciplina laboral', 'Conflictos colectivos'],
      blandas: ['Negociación', 'Empatía', 'Manejo de conflictos', 'Comunicación asertiva'],
      herramientas: ['Errepar', 'SAP HCM', 'MS Office'],
      certificaciones: ['Abogado / Especialización en derecho del trabajo'],
    },
    descripcionTipica: 'Especialista en relaciones laborales con experiencia en negociación colectiva y gestión de conflictos.',
  },
  {
    id: 'rrhh-chro-lead',
    rubro: 'RRHH',
    perfil: 'CHRO / Director de RRHH',
    nivel: 'Lead',
    skills: {
      tecnicas: ['Estrategia de personas', 'Transformación cultural', 'People analytics', 'Gestión del talento', 'Diversidad e inclusión'],
      blandas: ['Visión estratégica', 'Liderazgo', 'Influencia ejecutiva', 'Comunicación al board'],
      herramientas: ['Workday', 'SuccessFactors', 'Power BI', 'Tableau'],
      certificaciones: ['MBA', 'SHRM-SCP', 'Coaching ejecutivo'],
    },
    descripcionTipica: 'CHRO con experiencia liderando la función de personas en organizaciones medianas y grandes de LATAM.',
  },

  /* ═══════════════════════════════════════════════════════
     OPERACIONES / LOGÍSTICA (10 perfiles)
  ═══════════════════════════════════════════════════════ */
  {
    id: 'operaciones-logistica-senior',
    rubro: 'Operaciones',
    perfil: 'Jefe de Logística',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Supply Chain', 'Gestión de inventarios', 'Lean Manufacturing', 'KPIs operativos', 'Licitaciones'],
      blandas: ['Liderazgo', 'Resolución de conflictos', 'Gestión de equipos', 'Orientación al resultado'],
      herramientas: ['SAP', 'WMS', 'Excel Avanzado', 'Power BI', 'TMS'],
      certificaciones: ['APICS CPIM'],
    },
    descripcionTipica: 'Jefe de logística con experiencia en optimización de cadenas de suministro y gestión de equipos.',
  },
  {
    id: 'operaciones-scm-semi',
    rubro: 'Operaciones',
    perfil: 'Analista de Supply Chain',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Planificación de demanda', 'S&OP', 'Gestión de proveedores', 'CPFR', 'Análisis de inventario'],
      blandas: ['Analítico', 'Trabajo en equipo cross-funcional', 'Comunicación', 'Organización'],
      herramientas: ['SAP APO', 'Excel', 'Power BI', 'Kinaxis'],
      certificaciones: ['APICS CSCP'],
    },
    descripcionTipica: 'Analista de supply chain con experiencia en planificación integrada y gestión de inventarios.',
  },
  {
    id: 'operaciones-compras-semi',
    rubro: 'Operaciones',
    perfil: 'Analista de Compras / Procurement',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Negociación con proveedores', 'Licitaciones', 'Contratos', 'Homologación', 'Ahorro en compras', 'Sourcing estratégico'],
      blandas: ['Negociación', 'Ética', 'Organización', 'Orientación al ahorro'],
      herramientas: ['SAP MM', 'Ariba', 'Excel', 'Jaggaer'],
      certificaciones: ['CIPS', 'ISM CPP'],
    },
    descripcionTipica: 'Analista de compras con experiencia en gestión de proveedores y negociación de contratos.',
  },
  {
    id: 'operaciones-produccion-senior',
    rubro: 'Operaciones',
    perfil: 'Jefe de Producción',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Gestión de planta', 'Lean/Six Sigma', 'TPM', 'OEE', 'Seguridad industrial', 'BPM'],
      blandas: ['Liderazgo', 'Trabajo bajo presión', 'Toma de decisiones rápida', 'Comunicación'],
      herramientas: ['SAP PP', 'Excel', 'MES Systems'],
      certificaciones: ['Six Sigma Green Belt', 'TPM'],
    },
    descripcionTipica: 'Jefe de producción con experiencia en gestión de planta industrial y mejora continua.',
  },
  {
    id: 'operaciones-deposito-semi',
    rubro: 'Operaciones',
    perfil: 'Jefe de Depósito / Warehouse Manager',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Gestión de almacén', 'Inventario', 'Recepción y despacho', 'WMS', 'KPIs de warehouse', 'FIFO/FEFO'],
      blandas: ['Liderazgo operativo', 'Organización', 'Resolución de problemas', 'Trabajo en equipo'],
      herramientas: ['WMS (Manhattan/Blue Yonder)', 'SAP WM', 'Excel', 'RF scanners'],
      certificaciones: [],
    },
    descripcionTipica: 'Jefe de depósito con experiencia en gestión de almacenes y equipos operativos.',
  },
  {
    id: 'operaciones-mejora-senior',
    rubro: 'Operaciones',
    perfil: 'Gerente de Mejora Continua',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Lean Manufacturing', 'Six Sigma', 'Kaizen', 'DMAIC', 'VSM', 'Gestión de proyectos de mejora'],
      blandas: ['Facilitación', 'Liderazgo del cambio', 'Pensamiento sistémico', 'Influencia sin autoridad'],
      herramientas: ['Minitab', 'MS Project', 'Visio', 'Power BI'],
      certificaciones: ['Six Sigma Black Belt', 'PMP'],
    },
    descripcionTipica: 'Líder de mejora continua con experiencia en transformación operacional usando Lean Six Sigma.',
  },
  {
    id: 'operaciones-transporte-semi',
    rubro: 'Operaciones',
    perfil: 'Coordinador de Transporte y Distribución',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Gestión de flota', 'Ruteo', 'Costos de transporte', 'Last-mile', 'KPIs de distribución'],
      blandas: ['Organización', 'Resolución de problemas bajo presión', 'Negociación con transportistas'],
      herramientas: ['TMS', 'GPS tracking', 'SAP TM', 'Excel', 'Google Maps API'],
      certificaciones: [],
    },
    descripcionTipica: 'Coordinador de transporte con experiencia en gestión de distribución y optimización de rutas.',
  },
  {
    id: 'operaciones-planeamiento-junior',
    rubro: 'Operaciones',
    perfil: 'Planificador de Producción / Demand Planner',
    nivel: 'Junior',
    skills: {
      tecnicas: ['Planificación de producción', 'MRP', 'Forecast básico', 'Balance de línea', 'Control de stocks'],
      blandas: ['Organización', 'Comunicación', 'Analítico', 'Proactividad'],
      herramientas: ['SAP PP/MM', 'Excel', 'Power BI'],
      certificaciones: [],
    },
    descripcionTipica: 'Planificador con experiencia en programación de producción y control de materiales.',
  },
  {
    id: 'operaciones-calidad-semi',
    rubro: 'Operaciones',
    perfil: 'Analista de Calidad',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Control de calidad', 'ISO 9001', 'GMP', 'HACCP', 'Auditorías de calidad', 'Análisis de causa raíz'],
      blandas: ['Atención al detalle', 'Pensamiento sistemático', 'Comunicación escrita', 'Ética'],
      herramientas: ['SAP QM', 'Minitab', 'Excel', 'ISO management tools'],
      certificaciones: ['Auditor ISO 9001', 'HACCP'],
    },
    descripcionTipica: 'Analista de calidad con experiencia en sistemas de gestión ISO y auditorías de procesos.',
  },
  {
    id: 'operaciones-ehs-senior',
    rubro: 'Operaciones',
    perfil: 'Especialista EHS / HSE',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Seguridad e higiene', 'OHSAS 18001/ISO 45001', 'Evaluación de riesgos', 'Medio ambiente', 'Accidentología'],
      blandas: ['Comunicación', 'Compromiso con seguridad', 'Liderazgo', 'Formación de equipos'],
      herramientas: ['Intelex', 'SAP EHS', 'Excel', 'Sistemas de reporte de incidentes'],
      certificaciones: ['Licenciatura en HSE', 'ISO 45001 Auditor'],
    },
    descripcionTipica: 'Especialista en seguridad, salud y medio ambiente con experiencia en industrias reguladas.',
  },

  /* ═══════════════════════════════════════════════════════
     ATENCIÓN AL CLIENTE / CX (10 perfiles)
  ═══════════════════════════════════════════════════════ */
  {
    id: 'cx-customer-success-semi',
    rubro: 'Atención al Cliente',
    perfil: 'Customer Success Manager',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Onboarding de clientes', 'NPS/CSAT', 'Churn reduction', 'Upsell/Cross-sell', 'Health score', 'QBR'],
      blandas: ['Empatía', 'Comunicación', 'Proactividad', 'Orientación al cliente', 'Problem solving'],
      herramientas: ['Gainsight', 'Salesforce', 'HubSpot', 'Intercom', 'Zendesk'],
      certificaciones: ['CSM Certification (SuccessCoaching)'],
    },
    descripcionTipica: 'Customer Success Manager con experiencia en retención y expansión de cuentas SaaS en LATAM.',
  },
  {
    id: 'cx-soporte-junior',
    rubro: 'Atención al Cliente',
    perfil: 'Agente de Soporte N1',
    nivel: 'Junior',
    skills: {
      tecnicas: ['Atención al cliente', 'Gestión de tickets', 'Resolución de problemas básicos', 'Escalamiento', 'FAQ'],
      blandas: ['Paciencia', 'Empatía', 'Comunicación clara', 'Orientación al servicio'],
      herramientas: ['Zendesk', 'Freshdesk', 'Intercom', 'Slack', 'HubSpot'],
      certificaciones: [],
    },
    descripcionTipica: 'Agente de soporte de primer nivel con foco en resolución rápida y satisfacción del cliente.',
  },
  {
    id: 'cx-soporte-n2-semi',
    rubro: 'Atención al Cliente',
    perfil: 'Agente de Soporte N2 / Técnico',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Soporte técnico avanzado', 'Diagnóstico de problemas', 'SQL básico', 'APIs', 'Integraciones', 'Documentación técnica'],
      blandas: ['Pensamiento analítico', 'Comunicación técnica', 'Paciencia', 'Trabajo en equipo'],
      herramientas: ['Zendesk', 'JIRA', 'Postman', 'SQL', 'Confluence'],
      certificaciones: [],
    },
    descripcionTipica: 'Soporte técnico N2 con capacidad para resolver problemas complejos y colaborar con producto.',
  },
  {
    id: 'cx-analyst-semi',
    rubro: 'Atención al Cliente',
    perfil: 'CX Analyst',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['VOC (Voice of Customer)', 'NPS', 'Journey mapping', 'A/B Testing CX', 'Análisis de datos CX', 'Encuestas'],
      blandas: ['Analítico', 'Empatía estratégica', 'Comunicación', 'Presentación de insights'],
      herramientas: ['Medallia', 'Qualtrics', 'Google Analytics', 'Tableau', 'SurveyMonkey'],
      certificaciones: ['CX Professional (CXPA)'],
    },
    descripcionTipica: 'Analista CX especializado en medir y mejorar la experiencia del cliente basado en datos.',
  },
  {
    id: 'cx-help-desk-junior',
    rubro: 'Atención al Cliente',
    perfil: 'Help Desk IT',
    nivel: 'Junior',
    skills: {
      tecnicas: ['Soporte técnico básico', 'Active Directory', 'Windows/Mac troubleshooting', 'VPN', 'Office 365', 'ITIL'],
      blandas: ['Paciencia', 'Comunicación', 'Orientación al usuario', 'Trabajo bajo presión'],
      herramientas: ['ServiceNow', 'Jira Service Management', 'TeamViewer', 'AnyDesk'],
      certificaciones: ['CompTIA A+', 'ITIL Foundation'],
    },
    descripcionTipica: 'Help desk con experiencia en soporte técnico a usuarios finales y gestión de incidentes TI.',
  },
  {
    id: 'cx-manager-senior',
    rubro: 'Atención al Cliente',
    perfil: 'Customer Experience Manager',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Estrategia CX', 'Gestión de equipos CS', 'KPIs de servicio', 'Procesos de atención', 'Omnicanalidad'],
      blandas: ['Liderazgo', 'Empatía estratégica', 'Orientación al dato', 'Comunicación ejecutiva'],
      herramientas: ['Salesforce Service Cloud', 'Genesys', 'Medallia', 'Power BI'],
      certificaciones: ['CCXP (Certified CX Professional)'],
    },
    descripcionTipica: 'Manager de CX con experiencia en diseño de estrategias omnicanal y gestión de equipos.',
  },
  {
    id: 'cx-community-support-semi',
    rubro: 'Atención al Cliente',
    perfil: 'Community Support Specialist',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Moderación de comunidades', 'Gestión de reseñas', 'Crisis de reputación', 'Social listening', 'Respuesta en redes'],
      blandas: ['Empatía', 'Redacción persuasiva', 'Calma bajo presión', 'Discernimiento'],
      herramientas: ['Sprout Social', 'Hootsuite', 'Khoros', 'Zendesk', 'Google Business'],
      certificaciones: [],
    },
    descripcionTipica: 'Especialista en soporte de comunidades online con foco en reputación y satisfacción digital.',
  },
  {
    id: 'cx-chatbot-semi',
    rubro: 'Atención al Cliente',
    perfil: 'Conversational AI / Chatbot Specialist',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Diseño conversacional', 'NLU/NLP', 'Chatbot flows', 'Entrenamiento de modelos', 'Analytics de conversación'],
      blandas: ['Empatía con el usuario', 'Pensamiento lógico', 'Creatividad', 'Atención al detalle'],
      herramientas: ['Dialogflow', 'IBM Watson', 'Rasa', 'Botpress', 'Intercom'],
      certificaciones: [],
    },
    descripcionTipica: 'Especialista en diseño de chatbots y automatización de atención al cliente con IA conversacional.',
  },
  {
    id: 'cx-call-center-junior',
    rubro: 'Atención al Cliente',
    perfil: 'Operador de Call Center',
    nivel: 'Junior',
    skills: {
      tecnicas: ['Atención telefónica', 'Gestión de reclamos', 'Ventas por teléfono', 'Scripts', 'CRM básico'],
      blandas: ['Dicción clara', 'Paciencia', 'Escucha activa', 'Manejo de objeciones'],
      herramientas: ['Five9', 'Genesys', 'Avaya', 'Salesforce', 'Zendesk'],
      certificaciones: [],
    },
    descripcionTipica: 'Operador de call center con experiencia en atención inbound/outbound y gestión de reclamos.',
  },
  {
    id: 'cx-director-lead',
    rubro: 'Atención al Cliente',
    perfil: 'Director de Operaciones / VP Customer',
    nivel: 'Lead',
    skills: {
      tecnicas: ['P&L de operaciones', 'SLAs', 'Workforce management', 'Automatización de servicio', 'Omnicanalidad'],
      blandas: ['Liderazgo de grandes equipos', 'Visión estratégica', 'Comunicación ejecutiva', 'Orientación al cliente'],
      herramientas: ['Salesforce Service Cloud', 'Genesys', 'Tableau', 'Power BI'],
      certificaciones: ['MBA', 'CCXP'],
    },
    descripcionTipica: 'Director de operaciones de servicio con experiencia liderando centros de contacto en LATAM.',
  },

  /* ═══════════════════════════════════════════════════════
     LEGAL / COMPLIANCE (10 perfiles)
  ═══════════════════════════════════════════════════════ */
  {
    id: 'legal-abogado-semi',
    rubro: 'Legal',
    perfil: 'Abogado Corporativo',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Derecho Comercial', 'Contratos', 'Derecho Laboral', 'Due Diligence', 'Compliance'],
      blandas: ['Redacción', 'Negociación', 'Atención al detalle', 'Confidencialidad'],
      herramientas: ['LexisNexis', 'MS Office', 'DocuSign', 'iManage'],
      certificaciones: [],
    },
    descripcionTipica: 'Abogado corporativo con experiencia en contratos y asesoría legal empresarial.',
  },
  {
    id: 'legal-laboral-senior',
    rubro: 'Legal',
    perfil: 'Abogado Laboral Senior',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Derecho del trabajo', 'CCT', 'Negociación sindical', 'Litigios laborales', 'Despidos', 'ART'],
      blandas: ['Negociación', 'Comunicación', 'Manejo del estrés', 'Estrategia legal'],
      herramientas: ['LexisNexis', 'Errepar', 'Sistema SICOSS AFIP'],
      certificaciones: ['Especialización en derecho del trabajo'],
    },
    descripcionTipica: 'Abogado laboral con experiencia en conflictos individuales y colectivos de trabajo.',
  },
  {
    id: 'legal-compliance-senior',
    rubro: 'Legal',
    perfil: 'Compliance Officer',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Programas de compliance', 'Anti-corrupción (FCPA/UK Bribery)', 'AML', 'Gobierno corporativo', 'Política interna', 'Capacitación'],
      blandas: ['Ética', 'Confidencialidad', 'Influencia', 'Comunicación ejecutiva'],
      herramientas: ['NAVEX Global', 'SAP GRC', 'Excel', 'PowerPoint'],
      certificaciones: ['CCEP (Certified Compliance & Ethics Professional)'],
    },
    descripcionTipica: 'Compliance officer con experiencia en diseño de programas de integridad para empresas en LATAM.',
  },
  {
    id: 'legal-ip-semi',
    rubro: 'Legal',
    perfil: 'Especialista en Propiedad Intelectual',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Marcas', 'Patentes', 'Derechos de autor', 'Gestión de portfolio IP', 'Litigios IP', 'Contratos de licencia'],
      blandas: ['Atención al detalle', 'Investigación', 'Redacción técnica', 'Negociación'],
      herramientas: ['INPI', 'EUIPO', 'USPTO databases', 'Darts-IP', 'MS Office'],
      certificaciones: [],
    },
    descripcionTipica: 'Especialista en propiedad intelectual con experiencia en gestión de marcas y patentes en LATAM.',
  },
  {
    id: 'legal-privacidad-semi',
    rubro: 'Legal',
    perfil: 'DPO / Especialista en Privacidad',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['RGPD/GDPR', 'LGPD Brasil', 'Ley 25.326 Argentina', 'Evaluaciones de impacto', 'Contratos de datos', 'Incidentes de seguridad'],
      blandas: ['Actualización constante', 'Comunicación técnica', 'Integridad', 'Proactividad'],
      herramientas: ['OneTrust', 'TrustArc', 'MS Office'],
      certificaciones: ['CIPP/E', 'CIPM'],
    },
    descripcionTipica: 'DPO con experiencia en programas de privacidad de datos bajo normativas locales e internacionales.',
  },
  {
    id: 'legal-analyst-junior',
    rubro: 'Legal',
    perfil: 'Analista Legal Junior',
    nivel: 'Junior',
    skills: {
      tecnicas: ['Redacción de contratos', 'Investigación jurídica', 'Gestión documental', 'Apoyo en litigios', 'Legalización'],
      blandas: ['Atención al detalle', 'Confidencialidad', 'Organización', 'Aprendizaje continuo'],
      herramientas: ['LexisNexis', 'MS Office', 'DocuSign', 'Sistemas tribunales'],
      certificaciones: [],
    },
    descripcionTipica: 'Analista legal junior con apoyo en contratos, investigaciones jurídicas y gestión documental.',
  },
  {
    id: 'legal-regulatorio-senior',
    rubro: 'Legal',
    perfil: 'Abogado Regulatorio',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Regulación sectorial', 'Relaciones con reguladores', 'Autorización de productos', 'Lobby regulatorio', 'Farma/Fintech/Telecom'],
      blandas: ['Estrategia regulatoria', 'Comunicación gubernamental', 'Pensamiento sistémico'],
      herramientas: ['Bases regulatorias', 'MS Office'],
      certificaciones: ['Especialización en derecho administrativo o regulatorio'],
    },
    descripcionTipica: 'Abogado regulatorio con experiencia en gestión de relaciones con entes reguladores de LATAM.',
  },
  {
    id: 'legal-ma-senior',
    rubro: 'Legal',
    perfil: 'Abogado de M&A y Corporate Finance',
    nivel: 'Senior',
    skills: {
      tecnicas: ['M&A', 'Due diligence', 'Estructuración de operaciones', 'Contratos SPA/SHA', 'Capital markets', 'PE/VC'],
      blandas: ['Trabajo bajo presión extrema', 'Negociación', 'Gestión de transacciones complejas'],
      herramientas: ['VDR (Datasite/Intralinks)', 'Bloomberg', 'MS Office', 'DocuSign'],
      certificaciones: [],
    },
    descripcionTipica: 'Abogado corporativo especializado en M&A con experiencia en deal-making en LATAM.',
  },
  {
    id: 'legal-contratos-semi',
    rubro: 'Legal',
    perfil: 'Contract Manager',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Redacción y revisión de contratos', 'Negociación contractual', 'CLM', 'Riesgos contractuales', 'Contratos internacionales'],
      blandas: ['Atención al detalle', 'Negociación', 'Gestión del tiempo', 'Comunicación'],
      herramientas: ['Ironclad', 'DocuSign CLM', 'MS Word', 'Jira'],
      certificaciones: ['NCMA CCCM'],
    },
    descripcionTipica: 'Contract manager con experiencia en gestión del ciclo completo de contratos comerciales.',
  },
  {
    id: 'legal-gerente-lead',
    rubro: 'Legal',
    perfil: 'Gerente / Director Legal (General Counsel)',
    nivel: 'Lead',
    skills: {
      tecnicas: ['Estrategia legal corporativa', 'Litigios estratégicos', 'M&A', 'Gobierno corporativo', 'Compliance', 'Board advisory'],
      blandas: ['Liderazgo', 'Visión estratégica', 'Comunicación ejecutiva', 'Toma de decisiones'],
      herramientas: ['LexisNexis', 'MS Office', 'SAP', 'iManage'],
      certificaciones: ['MBA', 'Posgrado en Derecho de Empresas'],
    },
    descripcionTipica: 'General Counsel con experiencia liderando áreas legales en empresas medianas y grandes de LATAM.',
  },

  /* ═══════════════════════════════════════════════════════
     INGENIERÍA / INDUSTRIA (10 perfiles)
  ═══════════════════════════════════════════════════════ */
  {
    id: 'ingenieria-mecanica-senior',
    rubro: 'Ingeniería',
    perfil: 'Ingeniero Mecánico',
    nivel: 'Senior',
    skills: {
      tecnicas: ['AutoCAD', 'SolidWorks', 'Análisis estructural', 'Gestión de proyectos', 'ISO 9001', 'Mantenimiento predictivo'],
      blandas: ['Trabajo en equipo', 'Planificación', 'Liderazgo técnico', 'Resolución de problemas'],
      herramientas: ['AutoCAD', 'SolidWorks', 'ANSYS', 'MS Project', 'SAP PM'],
      certificaciones: ['PMP', 'Six Sigma Green Belt'],
    },
    descripcionTipica: 'Ingeniero mecánico con experiencia en diseño, manufactura y gestión de proyectos industriales.',
  },
  {
    id: 'ingenieria-industrial-semi',
    rubro: 'Ingeniería',
    perfil: 'Ingeniero Industrial',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Optimización de procesos', 'Estadística industrial', 'Lean', 'Layout de planta', 'Ergonomía', 'Simulación'],
      blandas: ['Analítico', 'Trabajo en equipo', 'Orientación a resultados', 'Comunicación'],
      herramientas: ['ProModel', 'Arena', 'AutoCAD', 'Excel', 'Minitab'],
      certificaciones: ['Six Sigma Green Belt', 'Lean Expert'],
    },
    descripcionTipica: 'Ingeniero industrial con experiencia en optimización de procesos productivos y de servicio.',
  },
  {
    id: 'ingenieria-electrica-senior',
    rubro: 'Ingeniería',
    perfil: 'Ingeniero Eléctrico',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Instalaciones eléctricas', 'MT/AT', 'SCADA', 'PLC', 'Proyectos de energía', 'Normativa eléctrica'],
      blandas: ['Seguridad', 'Rigor técnico', 'Liderazgo de equipos', 'Planificación'],
      herramientas: ['AutoCAD Electrical', 'ETAP', 'EPLAN', 'SAP PM'],
      certificaciones: ['Habilitación eléctrica matriculada'],
    },
    descripcionTipica: 'Ingeniero eléctrico con experiencia en proyectos de instalaciones y subestaciones eléctricas.',
  },
  {
    id: 'ingenieria-electronica-semi',
    rubro: 'Ingeniería',
    perfil: 'Ingeniero Electrónico / Embedded',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Diseño de circuitos', 'Firmware (C/C++)', 'IoT', 'PCB', 'Microcontroladores', 'Protocolos industriales'],
      blandas: ['Pensamiento sistémico', 'Atención al detalle', 'Investigación', 'Trabajo en equipo'],
      herramientas: ['Altium Designer', 'Oscilloscopio', 'Arduino', 'Raspberry Pi', 'KiCad'],
      certificaciones: [],
    },
    descripcionTipica: 'Ingeniero electrónico con experiencia en desarrollo de hardware y firmware para sistemas embebidos.',
  },
  {
    id: 'ingenieria-civil-senior',
    rubro: 'Ingeniería',
    perfil: 'Ingeniero Civil / Director de Obra',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Dirección de obra', 'Cómputo métrico', 'Estructuras', 'Hormigón', 'Licitaciones de obra', 'Normas ACI/CIRSOC'],
      blandas: ['Liderazgo', 'Gestión de equipos', 'Toma de decisiones', 'Comunicación con cliente'],
      herramientas: ['AutoCAD', 'Revit', 'MS Project', 'SAP', 'Civil 3D'],
      certificaciones: ['PMP', 'Matrícula de ingeniero'],
    },
    descripcionTipica: 'Ingeniero civil con experiencia en dirección de obras de infraestructura y edificación.',
  },
  {
    id: 'ingenieria-alimentos-semi',
    rubro: 'Ingeniería',
    perfil: 'Ingeniero en Alimentos / Bromatólogo',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['BPM', 'HACCP', 'Normativa FDA/ANMAT', 'Desarrollo de productos', 'Análisis sensorial', 'Microbiología'],
      blandas: ['Atención al detalle', 'Trabajo en equipo', 'Pensamiento analítico', 'Ética'],
      herramientas: ['SAP QM', 'Excel', 'Sistemas LIMS'],
      certificaciones: ['FSSC 22000', 'SQF Practitioner'],
    },
    descripcionTipica: 'Ingeniero en alimentos con experiencia en aseguramiento de calidad y desarrollo de productos.',
  },
  {
    id: 'ingenieria-quimica-semi',
    rubro: 'Ingeniería',
    perfil: 'Ingeniero Químico / de Procesos',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Procesos químicos', 'Balance de masa y energía', 'Seguridad química', 'Instrumentación', 'GMP', 'Destilación/Reacción'],
      blandas: ['Rigor técnico', 'Seguridad', 'Trabajo en equipo', 'Analítico'],
      herramientas: ['Aspen Plus', 'HYSYS', 'AutoCAD P&ID', 'SAP'],
      certificaciones: ['OSHA 30 horas', 'Matrícula profesional'],
    },
    descripcionTipica: 'Ingeniero químico con experiencia en diseño y optimización de procesos industriales.',
  },
  {
    id: 'ingenieria-mantenimiento-senior',
    rubro: 'Ingeniería',
    perfil: 'Jefe de Mantenimiento Industrial',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Mantenimiento predictivo', 'TPM', 'Análisis de fallas (RCA)', 'Gestión de activos', 'CMMS', 'Electricidad/Mecánica'],
      blandas: ['Liderazgo', 'Gestión bajo presión', 'Planificación', 'Toma de decisiones'],
      herramientas: ['SAP PM', 'Maximo', 'Excel', 'Termografía', 'Análisis de vibraciones'],
      certificaciones: ['CMRP (Certified Maintenance & Reliability Professional)'],
    },
    descripcionTipica: 'Jefe de mantenimiento con experiencia en gestión de activos industriales y mantenimiento predictivo.',
  },
  {
    id: 'ingenieria-ambiental-semi',
    rubro: 'Ingeniería',
    perfil: 'Ingeniero Ambiental',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Evaluación de impacto ambiental', 'ISO 14001', 'Gestión de residuos', 'Remediación', 'Permisos ambientales'],
      blandas: ['Ética ambiental', 'Comunicación', 'Pensamiento sistémico', 'Organización'],
      herramientas: ['ArcGIS', 'AutoCAD', 'Excel', 'Sistemas de gestión ambiental'],
      certificaciones: ['ISO 14001 Auditor', 'Matrícula ambiental'],
    },
    descripcionTipica: 'Ingeniero ambiental con experiencia en gestión de impacto ambiental y sistemas ISO 14001.',
  },
  {
    id: 'ingenieria-pm-senior',
    rubro: 'Ingeniería',
    perfil: 'Project Manager de Ingeniería',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Gestión de proyectos', 'PMI/PMBOK', 'Ingeniería de valor', 'Gestión de riesgos', 'Contratos EPC', 'Presupuesto'],
      blandas: ['Liderazgo', 'Comunicación', 'Negociación', 'Gestión de stakeholders'],
      herramientas: ['MS Project', 'Primavera P6', 'SAP PS', 'Power BI', 'AutoCAD'],
      certificaciones: ['PMP', 'Prince2'],
    },
    descripcionTipica: 'Project manager de ingeniería con experiencia en proyectos EPC y obras industriales en LATAM.',
  },

  /* ═══════════════════════════════════════════════════════
     SALUD / HEALTHCARE (10 perfiles)
  ═══════════════════════════════════════════════════════ */
  {
    id: 'salud-enfermero-semi',
    rubro: 'Salud',
    perfil: 'Enfermero/a',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Cuidados intensivos', 'Administración de medicamentos', 'Triaje', 'Primeros auxilios', 'Monitoreo hemodinámico'],
      blandas: ['Empatía', 'Trabajo bajo presión', 'Comunicación con pacientes', 'Trabajo en equipo'],
      herramientas: ['HIS hospitalario', 'Equipos de monitoreo', 'Bombas de infusión'],
      certificaciones: ['BLS', 'ACLS', 'Matrícula de enfermería'],
    },
    descripcionTipica: 'Enfermero/a con experiencia en atención hospitalaria y cuidados críticos.',
  },
  {
    id: 'salud-medico-trabajo-senior',
    rubro: 'Salud',
    perfil: 'Médico del Trabajo',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Medicina del trabajo', 'Pre-ocupacionales', 'Accidentología laboral', 'Higiene industrial', 'ART', 'ANMAT'],
      blandas: ['Ética médica', 'Comunicación con empleados', 'Trabajo multidisciplinario'],
      herramientas: ['HIS', 'Sistemas de gestión médica', 'MS Office'],
      certificaciones: ['Especialización en Medicina del Trabajo', 'Matrícula médica'],
    },
    descripcionTipica: 'Médico del trabajo con experiencia en salud ocupacional y gestión de riesgos laborales.',
  },
  {
    id: 'salud-psicologo-semi',
    rubro: 'Salud',
    perfil: 'Psicólogo/a Clínico/a u Organizacional',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Evaluación psicológica', 'Psicoterapia', 'Diagnóstico DSM-5', 'Evaluación laboral', 'Assessment psicológico'],
      blandas: ['Escucha activa', 'Empatía', 'Confidencialidad', 'Comunicación asertiva'],
      herramientas: ['Plataformas de telepsicología', 'Tests psicométricos', 'HIS'],
      certificaciones: ['Matrícula profesional', 'Especialización clínica u organizacional'],
    },
    descripcionTipica: 'Psicólogo/a con experiencia en atención clínica o evaluación de candidatos y desarrollo organizacional.',
  },
  {
    id: 'salud-nutricionista-junior',
    rubro: 'Salud',
    perfil: 'Nutricionista / Dietista',
    nivel: 'Junior',
    skills: {
      tecnicas: ['Evaluación nutricional', 'Planes alimentarios', 'Educación nutricional', 'Laboratorios clínicos', 'Patologías crónicas'],
      blandas: ['Empatía', 'Comunicación', 'Motivación al paciente', 'Actualización continua'],
      herramientas: ['Software nutricional', 'Excel', 'Plataformas de telenutrición'],
      certificaciones: ['Matrícula profesional'],
    },
    descripcionTipica: 'Nutricionista con experiencia en diseño de planes alimentarios individualizados.',
  },
  {
    id: 'salud-kinesiologo-semi',
    rubro: 'Salud',
    perfil: 'Kinesiólogo / Fisioterapeuta',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Rehabilitación kinésica', 'Electroterapia', 'Kinesiotaping', 'Rehabilitación deportiva', 'Ergonomía', 'RPG'],
      blandas: ['Empatía', 'Paciencia', 'Trabajo en equipo', 'Comunicación con pacientes'],
      herramientas: ['Equipos de electroterapia', 'Camilla', 'Sistemas de historia clínica'],
      certificaciones: ['Matrícula', 'Especialización en kinesiología deportiva u ortopédica'],
    },
    descripcionTipica: 'Kinesiólogo con experiencia en rehabilitación ortopédica y deportiva.',
  },
  {
    id: 'salud-farmaceutico-semi',
    rubro: 'Salud',
    perfil: 'Farmacéutico/a',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Dispensación de medicamentos', 'Farmacología clínica', 'Control de calidad', 'BPF', 'Regulación ANMAT/COFEPRIS'],
      blandas: ['Atención al detalle', 'Ética', 'Orientación al paciente', 'Trabajo en equipo'],
      herramientas: ['Sistemas de gestión farmacéutica', 'LIMS', 'Excel'],
      certificaciones: ['Matrícula profesional', 'Especialización en farmacia hospitalaria o clínica'],
    },
    descripcionTipica: 'Farmacéutico con experiencia en farmacia hospitalaria, retail o industria farmacéutica.',
  },
  {
    id: 'salud-biomedico-junior',
    rubro: 'Salud',
    perfil: 'Técnico Biomédico / Electromédico',
    nivel: 'Junior',
    skills: {
      tecnicas: ['Mantenimiento de equipos médicos', 'Electrónica médica', 'Gestión de activos médicos', 'Calibración', 'Normativa bioméd.'],
      blandas: ['Atención al detalle', 'Trabajo bajo presión', 'Resolución de problemas', 'Comunicación'],
      herramientas: ['Osciloscopio', 'Multímetro', 'CMMS hospitalario'],
      certificaciones: ['Matrícula de técnico', 'ACCE (Association for the Advancement of Medical Instrumentation)'],
    },
    descripcionTipica: 'Técnico biomédico con experiencia en mantenimiento y gestión de equipos médicos hospitalarios.',
  },
  {
    id: 'salud-medico-guardia-semi',
    rubro: 'Salud',
    perfil: 'Médico Clínico / Generalista',
    nivel: 'Semi-Senior',
    skills: {
      tecnicas: ['Atención clínica', 'Diagnóstico diferencial', 'Emergentología', 'Prescripción', 'Seguimiento crónico'],
      blandas: ['Toma de decisiones bajo presión', 'Empatía', 'Comunicación con pacientes y familia', 'Trabajo en equipo'],
      herramientas: ['HIS/EMR', 'Equipos diagnósticos', 'MS Office'],
      certificaciones: ['Matrícula médica', 'Especialidad en Clínica Médica'],
    },
    descripcionTipica: 'Médico clínico con experiencia en atención ambulatoria, guardia y seguimiento de pacientes crónicos.',
  },
  {
    id: 'salud-coordinador-semi',
    rubro: 'Salud',
    perfil: 'Coordinador/a de Salud / Head of Medical Affairs',
    nivel: 'Senior',
    skills: {
      tecnicas: ['Gestión clínica', 'Auditoría médica', 'KPIs de salud', 'Programas de salud', 'Acreditación JCI/IRAM'],
      blandas: ['Liderazgo', 'Gestión de equipos', 'Comunicación', 'Orientación al paciente'],
      herramientas: ['HIS/EMR', 'Power BI', 'Excel', 'SAP'],
      certificaciones: ['Especialidad médica', 'Gestión en salud'],
    },
    descripcionTipica: 'Coordinador de salud con experiencia en gestión de equipos clínicos y programas de calidad asistencial.',
  },
  {
    id: 'salud-director-lead',
    rubro: 'Salud',
    perfil: 'Director Médico / Director de Sanidad',
    nivel: 'Lead',
    skills: {
      tecnicas: ['Dirección médica', 'Estrategia sanitaria', 'Acreditación', 'Presupuesto de salud', 'Relaciones con obras sociales/prepagos'],
      blandas: ['Liderazgo', 'Visión estratégica', 'Comunicación ejecutiva', 'Ética médica'],
      herramientas: ['HIS Enterprise', 'Power BI', 'Tableau', 'SAP'],
      certificaciones: ['MBA en salud', 'Especialidad médica', 'Maestría en gestión sanitaria'],
    },
    descripcionTipica: 'Director médico con experiencia liderando instituciones o áreas de salud en LATAM.',
  },
]

export const rubros = [...new Set(skillsLibrary.map((s) => s.rubro))]

export function getProfilesByRubro(rubro: string): SkillProfile[] {
  return skillsLibrary.filter((s) => s.rubro === rubro)
}

export function searchProfiles(query: string): SkillProfile[] {
  const q = query.toLowerCase()
  return skillsLibrary.filter(
    (s) =>
      s.perfil.toLowerCase().includes(q) ||
      s.rubro.toLowerCase().includes(q) ||
      s.skills.tecnicas.some((t) => t.toLowerCase().includes(q)) ||
      s.descripcionTipica.toLowerCase().includes(q)
  )
}

export function getSkillsByProfile(profileId: string): string[] {
  const profile = skillsLibrary.find((s) => s.id === profileId)
  if (!profile) return []
  return [
    ...profile.skills.tecnicas,
    ...profile.skills.blandas,
    ...profile.skills.herramientas,
    ...(profile.skills.certificaciones ?? []),
  ]
}
